services:
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: monitoring_stack
    ports:
      - "80:80"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-data:/app/data
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    mem_limit: 1G
    restart: unless-stopped
    networks:
      - metrics_net

networks:
  metrics_net:
    external: true
