# Dockerfile
FROM python:3.10-slim

# Install dependencies (including wget)
RUN apt-get update && apt-get install -y supervisor nginx wget && rm -rf /var/lib/apt/lists/*

# Install Prometheus
RUN wget https://github.com/prometheus/prometheus/releases/download/v2.53.0/prometheus-2.53.0.linux-amd64.tar.gz && \
    tar xvfz prometheus-2.53.0.linux-amd64.tar.gz && \
    mv prometheus-2.53.0.linux-amd64/prometheus /usr/local/bin/ && \
    rm -rf prometheus-2.53.0.linux-amd64*

# Install Grafana
RUN wget https://dl.grafana.com/oss/release/grafana-11.1.0.linux-amd64.tar.gz && \
    tar xvfz grafana-11.1.0.linux-amd64.tar.gz && \
    mv grafana-v11.1.0 /usr/local/grafana && \
    rm grafana-11.1.0.linux-amd64.tar.gz

# Copy configuration files
COPY prometheus.dev.yml /etc/prometheus/prometheus.yml
COPY grafana.ini /usr/local/grafana/conf/custom.ini
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]